# Generated by Django 6.0.4 on 2026-04-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('regType', models.CharField(choices=[('Private', 'Private'), ('Government', 'Government'), ('Autonomous', 'Autonomous'), ('University', 'University')], max_length=20)),
            ],
        ),
    ]
