# Generated by Django 5.2 on 2026-04-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_admin_id_alter_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
